project:
  type: book

format: html
editor: visual

book:
  title: "Statistics Using Technology, 4th Edition"
  author: "Kathryn Kozak"
  date: "5/3/2025"
  cover-image: images/cover_picture.jpg
  cover-image-alt: "Barron Falls Australia"
  chapters:
    - index.qmd
    - Statistical Basics.qmd
    - Graphical Description of Data.qmd
    - Numerical Description of Data.qmd
    - Probability.qmd
    - Discrete Probability Distribution.qmd
    - Continuous Probability Distribution.qmd
    - One Sample Inference.qmd
    - Estimation.qmd
    - Two Sample Inference.qmd
    - Regression.qmd
    - Chi-Square and ANOVA Tests.qmd
    - References.qmd