project:
  type: book
  output-dir: Final_output
  resources:
    - "Rguroo_html_output/**"
  post-render:
    - scripts/make-pdf.sh

filters:
  - filters/class-to-macro.lua


format:
  html:
    css: styles.css
  pdf:
    pdf-engine: xelatex
    include-in-header: _preamble.tex
book:
  title: "Statistics Using Technology: Rguroo Edition"
  author:
    - name: "Kathryn Kozak"
      affiliation: "Coconino Community College"
    - name: "Alicia Frost"
      affiliation: "Santiago Canyon College"
    - name: "Mortaza Jamshidian"
      affiliation: "California State University, Fullerton"
    - name: "Jessica Kramer"
      affiliation: "Santiago Canyon College"
  date: "2026"
  cover-image: images/cover_picture.jpg
  chapters:
    - index.qmd
    - Statistical Basics.qmd
    - Graphical Description of Data.qmd
    - Numerical-description-of-Data.qmd
    - Probability.qmd
    - Discrete Probability Distribution.qmd
    - Continuous Probability Distribution.qmd
    - One Sample Inference.qmd
    - Estimation.qmd
    - Two Sample Inference.qmd
    - Regression.qmd
    - Chi-Square and ANOVA Tests.qmd
    - References.qmd