project:
  type: book
  output-dir: Final_output
  post-render:
    - scripts/make-pdf.sh

lua-filters:
  - filters/class-to-macro.lua

format:
  html:
    css: styles.css
  pdf:
    pdf-engine: xelatex
    include-in-header: _preamble.tex

book:
  title: "Statistics Using Technology: Rguroo Edition"
  author:
    - name: "Kathryn Kozak"
      affiliation: "Coconino Community College"
    - name: "John Doe"
      affiliation: "University of Example"
    - name: "Jane Smith"
      affiliation: "Northern Arizona University"
  date: "2026"
  cover-image: images/cover_picture.jpg
  chapters:
    - index.qmd
    - Statistical Basics.qmd
    - Graphical Description of Data.qmd
    - Numerical Description of Data.qmd
    - Probability.qmd
    - Discrete Probability Distribution.qmd
    - Continuous Probability Distribution.qmd
    - One Sample Inference.qmd
    - Estimation.qmd
    - Two Sample Inference.qmd
    - Regression.qmd
    - Chi-Square and ANOVA Tests.qmd
    - References.qmd